runtime: php55
api_version: 1

handlers:
- url: /.*
  script: cloud.php
  
  # [START env]
env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/a2rproject-148908:us-central1:myinstance;dbname=inventory
  MYSQL_USER: root
  MYSQL_PASSWORD: root@123
# [END env]


