application:a2rproject-148908
runtime: php55
service: my-service
api_version: 1

handlers:
- url: /.*
  script: cloud.php
  
env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/a2rproject-148908:us-central1:myinstance;port=3306;dbname=DATABASE
  MYSQL_USER: root
  MYSQL_PASSWORD: 'root@123'
